(define (problem RoadSystem_Problem)
(:domain RoadSystem)
(:objects
truck car bike pole - vehicle
A B C D E  - location)
(:init
    (at truck E)
    (at car A)
    (= (fuel-level truck) 100)
    (= (fuel-level car) 100)
    (accessible A B)
    (accessible B A)
    (accessible B E)
    (accessible E B)
    (accessible A C)
    (accessible C B)
    (accessible B C)
    (accessible B D)
    (accessible D B)

    (accessible E D)
    (accessible D E)
   ; (accessible E A)
   ; (accessible E B)
    (= (fuel-required A B) 40)
    (= (fuel-required B A) 40)
    (= (fuel-required B E) 30)
    (= (fuel-required E B) 30)
    (= (fuel-required A C) 20)
    (= (fuel-required C B) 25)
    (= (fuel-required B C) 25)
    (= (fuel-required B D) 22)
    (= (fuel-required D B) 21)
    (= (fuel-required E D) 50)
    (= (fuel-required D E) 35)
    ;(= (fuel-required E B) 40)
    ;(= (fuel-required B A) 40)
    (= (total-fuel-used) 0)
    (= (fuel-used car) 0)
    (= (fuel-used truck) 0)
)
(:goal (and (at truck A)
       (at car E))
)
(:metric minimize (total-fuel-used))


)